name: Placeholder
on:
    pull_request:
jobs:
  silly:
    runs-on: ubuntu-latest
    steps:
        - name: Placeholder
          run: |
            echo "Will add code checks here in next challenge"
